spring:
  application:
    name: blog
  servlet:
    multipart:
      max-file-size: 20MB       # 单个文件最大 20MB
      max-request-size: 50MB    # 请求总大小最大 50MB
  config:
    import: optional:classpath:application-secret.yml
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
server:
    port: 8080
    servlet:
      encoding:
          charset: UTF-8
          force: true
          enabled: true


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.x.entity
  type-handlers-package: com.x.utils
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      x:
        mapper: debug
        service: info
        controller: info



springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc
    tags-sorter: alpha
    operations-sorter: alpha


#api文档
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-model: true
    enable-document-manage: true
  cors: false
  production: false
